# Dataset-specific configurations

movielens-1m:
  url: https://files.grouplens.org/datasets/movielens/ml-1m.zip
  filename: ml-1m.zip
  format: movielens
  separator: "::"
  min_interactions: 5

goodreads:
  url: https://github.com/BahramJannesar/GoodreadsBookDataset
  format: goodreads
  min_interactions: 5

google-reviews:
  url: https://jiachengli1995.github.io/google/index.html
  format: google_reviews
  min_interactions: 5
